=== FRC2834/blackhawks-scouting/src/common/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "heading": { "type": "string" },
    "logo": { "type": "string" },
    "skipTeamSelection": { "type": "boolean" },
    "forceQualifiers": { "type": "boolean" },
    "pages": {
      "type": "array",
      "items": { "$ref": "#/$defs/page" }
    }
  },
  "required": ["pages"],
  "$defs": {
    "page": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "widgets": {
          "type": "array",
          "items": { "$ref": "#/$defs/widget" }
        }
      },
      "required": ["name", "widgets"]
    },
    "validationInequality": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": ["less", "lessOrEqual", "greater", "greaterOrEqual", "equal"]
        },
        "value": { "type": "integer" }
      },
      "required": ["value"]
    },
    "validationRange": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": ["inRange", "outOfRange"]
        },
        "value": {
          "type": "array",
          "items": { "type": "integer" }
        }
      },
      "required": ["value"]
    },
    "validation": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": ["less", "lessOrEqual", "greater", "greaterOrEqual", "equal", "inRange", "outOfRange"]
        }
      },
      "required": ["comparison"],
      "oneOf": [
        { "$ref": "#/$defs/validationInequality" },
        { "$ref": "#/$defs/validationRange" }
      ]
    },
    "widgetDropdown": {
      "type": "object",
      "properties": {
        "type": { "const": "dropdown" },
        "defaultOption": { "type": "boolean" },
        "options": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "required": ["name", "options"]
    },
    "widgetHeading": {
      "type": "object",
      "properties": {
        "type": { "const": "heading" }
      },
      "required": ["name"]
    },
    "widgetLabel": {
      "type": "object",
      "properties": {
        "type": { "const": "label" }
      },
      "required": ["name"]
    },
    "widgetText": {
      "type": "object",
      "properties": {
        "type": { "const": "text" }
      },
      "required": ["name"]
    },
    "widgetNumber": {
      "type": "object",
      "properties": {
        "type": { "const": "number" }
      },
      "required": ["name"]
    },
    "widgetCheckbox": {
      "type": "object",
      "properties": {
        "type": { "const": "checkbox" }
      },
      "required": ["name"]
    },
    "widgetMultiCheckbox": {
      "type": "object",
      "properties": {
        "type": { "const": "multicheckbox" },
        "options": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "required": ["name", "options"]
    },
    "widgetPicture": {
      "type": "object",
      "properties": {
        "type": { "const": "picture" },
        "file": { "type": "string" },
        "width": { "type": "integer" },
        "height": { "type": "integer" }
      },
      "required": ["file"]
    },
    "widgetPositions": {
      "type": "object",
      "properties": {
        "type": { "const": "positions" },
        "file": { "type": "string" },
        "width": { "type": "integer" },
        "height": { "type": "integer" },
        "allowMultiple": { "type": "boolean" },
        "selectRadius": { "type": "integer" },
        "selectColor": { "type": "string" }
      },
      "required": ["name", "file"]
    },
    "widgetRadio": {
      "type": "object",
      "properties": {
        "type": { "const": "radio" },
        "options": {
          "type": "array",
          "items": { "type": "string" }
        },
        "default": { "type": "integer" }
      },
      "required": ["name", "options"]
    },
    "widgetSpacer": {
      "type": "object",
      "properties": {
        "type": { "const": "spacer" },
        "width": { "type": "integer" },
        "height": { "type": "integer" }
      }
    },
    "widgetSpinbox": {
      "type": "object",
      "properties": {
        "type": { "const": "spinbox" },
        "min": { "type": "integer" },
        "max": { "type": "integer" },
        "allowKeyboardInput": { "type": "boolean" },
        "buttonColor": { "type": "string" }
      },
      "required": ["name"]
    },
    "widgetStopwatch": {
      "type": "object",
      "properties": {
        "type": { "const": "stopwatch" },
        "startLabel": { "type": "string" },
        "lapLabel": { "type": "string" },
        "stopLabel": { "type": "string" },
        "maxLaps": { "type": "integer" }
      },
      "required": ["name"]
    },
    "widgetTextarea": {
      "type": "object",
      "properties": {
        "type": { "const": "textarea" }
      },
      "required": ["name"]
    },
    "widgetToggleGrid": {
      "type": "object",
      "properties": {
        "type": { "const": "togglegrid" },
        "width": { "type": "integer" },
        "height": { "type": "integer" },
        "colors": {
          "type": "array",
          "items": { "type": "string" }
        },
        "rowColors": {
          "type": "array",
          "items": { "type": "string" }
        },
        "colColors": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "required": ["name", "width", "height", "colors"]
    },
    "widget": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["dropdown", "heading", "label", "text", "number", "checkbox", "multicheckbox", "picture", "positions", "radio", "spacer", "spinbox", "stopwatch", "textarea", "togglegrid"]
        },
        "prefix": { "type": "string" },
        "name": { "type": "string" },
        "align": {
          "type": "string",
          "enum": ["left", "center", "right"]
        },
        "noLabel": { "type": "boolean" },
        "row": { "type": "integer" },
        "col": { "type": "integer" },
        "rowspan": { "type": "integer" },
        "colspan": { "type": "integer" },
        "labelColspan": { "type": "integer" },
        "validation": { "$ref": "#/$defs/validation" }
      },
      "required": ["type"],
      "oneOf": [
        { "$ref": "#/$defs/widgetDropdown" },
        { "$ref": "#/$defs/widgetHeading" },
        { "$ref": "#/$defs/widgetLabel" },
        { "$ref": "#/$defs/widgetText" },
        { "$ref": "#/$defs/widgetNumber" },
        { "$ref": "#/$defs/widgetCheckbox" },
        { "$ref": "#/$defs/widgetMultiCheckbox" },
        { "$ref": "#/$defs/widgetPicture" },
        { "$ref": "#/$defs/widgetPositions" },
        { "$ref": "#/$defs/widgetRadio" },
        { "$ref": "#/$defs/widgetSpacer" },
        { "$ref": "#/$defs/widgetSpinbox" },
        { "$ref": "#/$defs/widgetStopwatch" },
        { "$ref": "#/$defs/widgetTextarea" },
        { "$ref": "#/$defs/widgetToggleGrid" }
      ]
    }
  }
}

=== FRC2834/blackhawks-scouting/public/assets/config-pits-2023.json
{
  "heading": "Charged Up - 2023 (Pit Scouting)",
  "logo": "logo.png",
  "skipTeamSelection": true,
  "pages": [
    {
      "name": "Team",
      "widgets": [
        {
          "name": "Team Number",
          "type": "number"
        },
        {
          "name": "Drive Coach",
          "type": "text"
        },
        {
          "name": "Driver Names",
          "type": "text"
        }
      ]
    },
    {
      "name": "Robot",
      "widgets": [
        {
          "name": "Height",
          "type": "number"
        },
        {
          "name": "Length",
          "type": "number"
        },
        {
          "name": "Width",
          "type": "number"
        },
        {
          "name": "Wheel-Bumper Distance",
          "type": "number"
        },
        {
          "name": "Weight",
          "type": "number"
        },
        {
          "name": "Drivetrain",
          "type": "dropdown",
          "options": [
            "West Coast",
            "Swerve",
            "Butterfly",
            "Mecanum",
            "Other"
          ]
        },
        {
          "name": "Swerve Motor Type",
          "type": "dropdown",
          "options": [
            "Neo",
            "Falcon",
            "Cim"
          ]
        },
        {
          "name": "Swerve Type",
          "type": "dropdown",
          "options": [
            "No swerve",
            "L1",
            "L2",
            "L3",
            "L4",
            "Neo",
            "Falcon",
            "Custom"
          ]
        },
        {
          "name": "Has Driver Camera",
          "type": "checkbox"
        }
      ]
    },
    {
      "name": "Match Play",
      "widgets": [
        {
          "name": "Cycle Time",
          "type": "number"
        },
        {
          "name": "Can Pick Up",
          "type": "multicheckbox",
          "options": [
            "Ground Upright Cones",
            "Ground Tipped Cones",
            "Ground Cubes",
            "Sub 1 (Direct)",
            "Sub 2 High"
          ]
        },
        {
          "name": "Can Score In",
          "type": "multicheckbox",
          "options": [
            "High Cone",
            "High Cube",
            "Medium Cone",
            "Medium Cube",
            "Low Cone",
            "Low Cube"
          ]
        },
        {
          "name": "Scoring Methods",
          "type": "multicheckbox",
          "options": [
            "Manual",
            "Auto"
          ]
        },
        {
          "name": "Preferred Pickup Location",
          "type": "dropdown",
          "options": [
            "Ground",
            "Sub 1",
            "Sub 2 Low",
            "Sub 2 High"
          ],
          "defaultOption": true
        },
        {
          "name": "Comments",
          "type": "textarea",
          "colspan": 3
        }
      ]
    }
  ]
}

=== FRC2834/blackhawks-scouting/public/assets/config-pits.json
{
  "heading": "Crescendo - 2024 (Pit Scouting)",
  "logo": "final4.png",
  "skipTeamSelection": true,
  "pages": [
    {
      "name": "Team",
      "widgets": [
        {
          "name": "Team Name",
          "type": "text"
        },
        {
          "name": "Team Number",
          "type": "number"
        }
      ]
    },
    {
      "name": "Robot",
      "widgets": [
        {
          "name": "Drivetrain",
          "type": "dropdown",
          "options": [
            "West Coast",
            "Swerve",
            "Butterfly",
            "Mecanum",
            "Tank Drive",
            "Other"
          ]
        },
        {
          "name": "can climb?",
          "type": "checkbox"
        }
      ]
    },
    {
      "name": "Match Play",
      "widgets": [
        {
          "name": "Cycle Time",
          "type": "number"
        },
        {
          "name": "Can Pick Up",
          "type": "multicheckbox",
          "options": [
            "Ground",
            "Source"
          ]
        },
        {
          "name": "Can Score In",
          "type": "multicheckbox",
          "options": [
            "Speaker",
            "Amp",
            "Trap"
          ]
        },
        {
          "name": "Scoring Methods",
          "type": "multicheckbox",
          "options": [
            "Manual",
            "Auto"
          ]
        },
        {
          "name": "Preferred Pickup Location",
          "type": "dropdown",
          "options": [
            "Ground",
            "Source"
          ],
          "defaultOption": true
        },
        {
          "name": "Preferred Pickup Location",
          "type": "dropdown",
          "options": [
            "Ground",
            "Source"
          ],
          "defaultOption": true
        },
        {
          "name": "Comments",
          "type": "textarea",
          "colspan": 3
        }
      ]
    }
  ]
}

=== FRC2834/blackhawks-scouting/public/assets/archive/2022/config-pits.json
{
  "heading": "Rapid React - 2022 (Pit Scouting)",
  "logo": "logo.png",
  "skipTeamSelection": true,
  "pages": [
    {
      "name": "Team",
      "widgets": [
        {
          "name": "Team Number",
          "type": "number"
        },
        {
          "name": "Drive Coach",
          "type": "text"
        },
        {
          "name": "Driver Names",
          "type": "text"
        }
      ]
    },
    {
      "name": "Robot",
      "widgets": [
        {
          "name": "Height",
          "type": "number"
        },
        {
          "name": "Weight",
          "type": "number"
        },
        {
          "name": "Drivetrain",
          "type": "dropdown",
          "options": [
            "West Coast",
            "Swerve",
            "Butterfly",
            "Mecanum",
            "Other"
          ]
        },
        {
          "name": "Has Driver Camera",
          "type": "checkbox"
        }
      ]
    },
    {
      "name": "Match Play",
      "widgets": [
        {
          "name": "Climb Time",
          "type": "number"
        },
        {
          "name": "Climb",
          "type": "radio",
          "options": [
            "None",
            "Low",
            "Mid",
            "High",
            "Traversal"
          ]
        },
        {
          "name": "Aiming Method",
          "type": "radio",
          "options": [
            "Manual Targeting",
            "Automatic"
          ]
        },
        {
          "name": "Comments",
          "type": "textarea",
          "colspan": 3
        }
      ]
    }
  ]
}
